AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample Item Application

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 100
    Tracing: Active
    Environment: 
      Variables:
        POWERTOOLS_SERVICE_NAME: powertools-java-sample-app
        POWERTOOLS_LOG_LEVEL: Debug
  Api:
    TracingEnabled: true

Resources:
  PostItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: item-api-post
      Handler: com.item.handler.PostItemHandler::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 1024
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref SampleTable
      Events:
        ItemPostEvent:
          Type: Api
          Properties:
            Path: /items
            Method: POST

  GetAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: item-api-get-all
      Handler: com.item.handler.GetAllItemsHandler::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 1024
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref SampleTable
      Events:
        ItemPostEvent:
          Type: Api
          Properties:
            Path: /items
            Method: GET

  GetItemByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: item-api-get-by-id
      Handler: com.item.handler.GetItemByIdHandler::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 1024
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref SampleTable
      Events:
        ItemPostEvent:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: GET

  # DynamoDB table to store item: {id: &lt;ID&gt;, name: &lt;NAME&gt;}
  SampleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: SampleAppItem
      PrimaryKey:
        Name: Id
        Type: Number 
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"
  SampleTable:
    Description: Sample Data Table ARN
    Value: !GetAtt SampleTable.Arn
