AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample API Lambda Powertools - Logging

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    TracingEnabled: true
    Cors:                               # https://awslabs.github.io/aws-lambda-powertools-python/latest/core/event_handler/api_gateway/#cors
        # AllowOrigin: "'https://example.com'"
        AllowOrigin: "'*'"  # Dev only
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date'"
        MaxAge: "'300'"
  Function:
      Timeout: 10
      MemorySize: 256
      Runtime: dotnet6
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: powertools-dotnet # This can also be set using the decorator on your handler e.g.[Metrics(Namespace = "aws-lambda-powertools"]
          POWERTOOLS_LOG_LEVEL: Debug
          POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
          POWERTOOLS_LOGGER_CASE: SnakeCase # Allowed values are: CamelCase, PascalCase and SnakeCase (default)
          POWERTOOLS_METRICS_NAMESPACE: AWSLambdaPowertools # This can also be set using the decorator on your handler [Metrics(Namespace = "aws-lambda-powertools"]
          POWERTOOLS_TRACER_CAPTURE_RESPONSE: true
          POWERTOOLS_TRACER_CAPTURE_ERROR: true     # To disable tracing (CaptureMode = TracingCaptureMode.Disabled)
      AutoPublishAlias: live # More info about Safe Deployments: https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute

Resources:
  SampleAppPTFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: Sample API Lambda Powertools - Logging Hello function
      CodeUri: ./sample-app-pt/
      Handler: sample-app-pt::SampleAppPT.Function::FunctionHandler
      Policies:
        - AWSXRayDaemonWriteAccess
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
              Path: /hello
              Method: get
      Tags:
          LambdaPowertools: dotnet

  GetAllItemsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: Sample API Lambda Powertools - Logging - GellAllItems function
      CodeUri: ./sample-app-pt/
      Handler: sample-app-pt::SampleAppPT.GetAllItems::FunctionHandler
      Policies:
        - AWSXRayDaemonWriteAccess
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
              Path: /getAllItems
              Method: get
      Tags:
          LambdaPowertools: dotnet

# log groups

  SampleAppPTFunctionLogGroup:
    Type: "AWS::Logs::LogGroup"
    DeletionPolicy: Delete
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub 
      - '/aws/lambda/${Function}'
      - Function: !Ref SampleAppPTFunction

  GetAllItemsLogGroup:
    Type: "AWS::Logs::LogGroup"
    DeletionPolicy: Delete
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub 
      - '/aws/lambda/${Function}'
      - Function: !Ref GetAllItemsFunction

Outputs:

    SampleAppPTApi:
      Description: "API Gateway endpoint URL for Prod environment for sample-app-pt Function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

    SampleAppPTFunctionArn:
      Description: "sample-app-pt Lambda Function ARN"
      Value: !GetAtt SampleAppPTFunction.Arn

    GetAllItemsFunctionArn:
      Description: "sample-app-pt Lambda GetAllItems ARN"
      Value: !GetAtt GetAllItemsFunction.Arn

    SampleAppPTFunctionIamRole:
      Description: "Implicit IAM Role created for sample-app-pt function"
      Value: !GetAtt SampleAppPTFunctionRole.Arn
    
    GetAllItemsFunctionIamRole:
      Description: "Implicit IAM Role created for sample-app-pt GetAllItems"
      Value: !GetAtt GetAllItemsFunction.Arn
