entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
      health_check_service: true
  buffer:
    bounded_blocking:
      buffer_size: 1024
      batch_size: 160
  sink:
    - pipeline:
        name: "raw-trace-pipeline"
    - pipeline:
        name: "service-map-pipeline"
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  buffer:
    bounded_blocking:
      buffer_size: 1024
      batch_size: 160
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
         hosts: [ "<OPENSEARCH_ENDPOINT>" ]
         aws_sigv4: true
         index_type: trace-analytics-raw
service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  buffer:
    bounded_blocking:
      buffer_size: 10240
      batch_size: 160
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
         hosts: [ "<OPENSEARCH_ENDPOINT>" ]
         aws_sigv4: true
         index_type: trace-analytics-service-map